export const LOGIN_VIA_EMAIL_REQUEST = "LOGIN_VIA_EMAIL_REQUEST";
export const LOGIN_VIA_EMAIL_SUCCESS = "LOGIN_VIA_EMAIL_SUCCESS";
export const LOGIN_VIA_EMAIL_ERROR = "LOGIN_VIA_EMAIL_ERROR";

export const SIGNUP_VIA_EMAIL_REQUEST = "SIGNUP_VIA_EMAIL_REQUEST";
export const SIGNUP_VIA_EMAIL_SUCCESS = "SIGNUP_VIA_EMAIL_SUCCESS";
export const SIGNUP_VIA_EMAIL_ERROR = "SIGNUP_VIA_EMAIL_ERROR";

export const LOGOUT_ACITON = "LOGOUT_ACITON";

export const VERIFY_OTP_REQUEST = "VERIFY_OTP__REQUEST";
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP__SUCCESS";
export const VERIFY_OTP__ERROR = "VERIFY_OTP__ERROR";
