export const ADD_PATIENT_REQUEST = "ADD_PATIENT__REQUEST";
export const ADD_PATIENT_SUCCESS = "ADD_PATIENT__SUCCESS";
export const ADD_PATIENT__ERROR = "ADD_PATIENT__ERROR";

export const PATIENT_LIST_REQUEST = "PATIENT_LIST_REQUEST";
export const PATIENT_LIST_SUCCESS = "PATIENT_LIST_SUCCESS";
export const PATIENT_LIST_ERROR = "PATIENT_LIST_ERROR";

export const PATIENT_HISTORY_REQUEST = "PATIENT_HISTORY_REQUEST";
export const PATIENT_HISTORY_SUCCESS = "PATIENT_HISTORY_SUCCESS";
export const PATIENT_HISTORY_ERROR = "PATIENT_HISTORY_ERROR";
